#include <iostream>
#include <sstream>
#include <fstream>
#include <zlib.h>
#include <lz4.h>
#include <vector>
#include <array>
#include <queue>
#include <string>
#include <cstring>
#include <math.h>
#include <numeric>
#include <assert.h>
#include <tuple>
#include <algorithm>
#include <list>
#include <limits>
#include <cstdint>
#include <sstream>
#include <memory>
#include <thread>
#include <mutex>
#include <atomic>
#include <chrono>
#include <stdexcept>
#include <utility>
#include <type_traits>
#include <boost/filesystem.hpp>
#include <boost/property_tree/xml_parser.hpp>
#include <boost/property_tree/ptree.hpp>
#include <boost/optional/optional.hpp>
#include <boost/foreach.hpp>
#include <seqan/basic.h>
#include <seqan/sequence.h>
#include <seqan/bam_io.h>
